config/routes.rb
Humhum::Application.routes.draw do
  resources :albums,        only: [:index, :create]
  resources :naver_albums,  only: [:index, :create]
  resources :daum_albums,   only: [:index, :create]
  resources :melon_albums,  only: [:index, :create]

  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  # Validation
  #   - all colums must be present
  #   - youtube hash must be unique
  #   - [title, artist] pair must be unique

  validates :title, presence: true
  validates :artist, presence: true
  validates :content_provider, presence: true

  validates :youtube_hash, presence: true,
                            uniqueness: true
  validates_uniqueness_of :title, scope: [:artist]
end

app/models/concerns/crawler.rb
module Crawler
  extend ActiveSupport::Concern

  def crawl_from(url) # url(string) -> html_source(string)
    require 'open-uri'
    require 'nokogiri'
    Nokogiri::HTML(open(url)) # return
  end
end

app/models/daum_album.rb
class DaumAlbum < Album
  # inherit from Album Model

  def self.get_albums(url) #using class method
    @albums = Array.new(50){ Hash.new }

    # PROCESS 1 : Crawl from Naver
    # PROCESS 2 : Parse 
    get_albums_from_content_provider(@albums, crawl_from(url).css("tr.track"))
    
    # PROCESS 3 : Search and Crawl from Youtube
    # PROCESS 4 : Parse
    get_albums_from_youtube(@albums)
  end


  # Implementation of Template
  def self.get_albums_from_content_provider(albums, source)
    albums.each_with_index do |album, index|
      album["title"] = parse_title source[index]
      album["artist"] = parse_artist source[index]
    end
  end

  def self.parse_title(source)
    source.css("a.CT_ZONE_LIST_SONG")[0]["title"]
  end

  def self.parse_artist(source)
    source.css("a.CT_ZONE_LIST_ARTIST")[0]["title"]
  end
end

app/models/melon_album.rb
class MelonAlbum < Album
  # inherit from Album Model

  def self.get_albums(url) #using class method
    @albums = Array.new(50){ Hash.new }

    # PROCESS 1 : Crawl from Naver
    # PROCESS 2 : Parse 
    get_albums_from_content_provider(@albums, crawl_from(url).css("tbody tr"))
    
    # PROCESS 3 : Search and Crawl from Youtube
    # PROCESS 4 : Parse
    get_albums_from_youtube(@albums)
  end


  # Implementation of Template
  def self.get_albums_from_content_provider(albums, source)
    albums.each_with_index do |album, index|
      album["title"] = parse_title source[index]
      album["artist"] = parse_artist source[index]
    end
  end

  def self.parse_title(source)
    source.css(".lineLine1 a")[1]["title"]
  end

  def self.parse_artist(source)
    source.css(".lineLine2 a")[0]["title"]
  end
end

app/models/naver_album.rb
class NaverAlbum < Album
  # inherit from Album Model

  def self.get_albums(url) #using class method
    @albums = Array.new(5){ Hash.new }

    # PROCESS 1 : Crawl from Naver
    # PROCESS 2 : Parse 
    get_albums_from_content_provider(@albums, crawl_from(url).css(".tm_section"))
    
    # PROCESS 3 : Search and Crawl from Youtube
    # PROCESS 4 : Parse
    get_albums_from_youtube(@albums)
  end


  # Implementation of Template
  def self.get_albums_from_content_provider(albums, source)
    albums.each_with_index do |album, index|
      album["title"] = parse_title source[index+1]
      album["artist"] = parse_artist source[index+1]

      # why parse form index+1?
      #   - source[0] is a dummy info
    end
  end

  def self.parse_title(source)
    source.css(".name").css("._title")[0]["title"]
  end

  def self.parse_artist(source)
    source.css("tbody td ._artist").css("._artist")[0]["title"]
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    # show all albums
    @albums = Album.all
  end

  def create
    album = YoutubeHashParser.get_album_from_youtube params[:custom_album_query]
    data = { youtube_hash: album["youtube_hash"] }
    render json: album.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daum_albums_controller.rb
class DaumAlbumsController < AlbumsController
  extend DaumParser

  def index
    # show all daum albums
    @daum_albums = Album.where(content_provider: "D")
  end

  def create
    @daum_albums = DaumParser.get_albums("http://music.daum.net/chart/chartsong/list")

    @daum_albums.each do |daum_album|
      Album.create(title: daum_album["title"], 
                        artist: daum_album["artist"],
                        youtube_hash: daum_album["youtube_hash"],
                        content_provider: "D")
    end

    redirect_to root_path
  end

end

app/controllers/melon_albums_controller.rb
class MelonAlbumsController < AlbumsController
  extend MelonParser

  def index
    # show all melon albums
    @melon_albums = Album.where(content_provider: "M")
  end

  def create
    @melon_albums = MelonParser.get_albums("http://www.melon.com/cds/chart/web/chartrealtime_list.htm")

    @melon_albums.each do |melon_album|
      Album.create(title: melon_album["title"],
                        artist: melon_album["artist"],
                        youtube_hash: melon_album["youtube_hash"],
                        content_provider: "M")
    end

    redirect_to root_path
  end
end

app/controllers/naver_albums_controller.rb
class NaverAlbumsController < AlbumsController
  extend NaverParser

  def index
    # show all naver albums
    @naver_albums = Album.where(content_provider: "N")
  end

  def create
    @naver_albums = NaverParser.get_albums("http://music.naver.com/todayMusic/index.nhn?startDate=20140210")

    @naver_albums.each do |naver_album|
      Album.create( title: naver_album["title"],
                    artist: naver_album["artist"],
                    youtube_hash: naver_album["youtube_hash"],
                    content_provider: "N" )
    end

    redirect_to root_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  include UrlGenerator
  include ContentProviderNameGenerator
  include YoutubeHashParser
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daum_albums_helper.rb
module DaumAlbumsHelper
end

app/helpers/melon_albums_helper.rb
module MelonAlbumsHelper
end

app/helpers/naver_albums_helper.rb
module NaverAlbumsHelper
end

app/views/albums/index.html.erb
<div id="main_page" class="col-sm-12">
  <div class="col-sm-12">
    <h2>FREE MUSIC PLAYER</h2>
  </div>

  <% # this is for search bar %>
  <div class="col-sm-12">
    <div class="col-sm-10">
      <%= text_field_tag "custom_album[query]", nil, class: "col-sm-8 form-control" %>
    </div>
    <div class="col-sm-2">
      <button type="submit" class="btn btn-primary", onclick="new_custom_album()">SEARCH</button>
    </div>
  </div>

  <div class="col-sm-12">
    <%= link_to "Parse Naver Album", naver_albums_path, method: :post %><br />
    <%= link_to "Parse Daum Album", daum_albums_path, method: :post %><br />
    <%= link_to "Parse Melon Album", melon_albums_path, method: :post %><br />
  </div>
</div>

<% # background image %>
<img src="" id="bg" alt="" />

<% # index controller has two concern %>
<% #    - provide custom music search %>
<% #    - show all albums %>

<% # this is alternative for albums#new  %>
<% # this is more user-friendly interface  %>


<% # using form_tag instead of form_for %>



<% # custom search feature and showing result feature should be implemented by AJAX %>
<% # using JSON for data transfer %>

<% if !@albums.nil? %>
  <div>
       <iframe id="youtube_player" src="" frameborder="0" width="0" height="0" ></iframe>
  </div>


  <% # view not yet implemented %>

  <% # PROBLEM : rendering N iframe is so slow %>
  <% # HOW TO SOLVE : implement custom player with javascript %>

  <div class="col-sm-12">
  <% @albums.each do |album| %>
    <div class="list-group col-sm-12" onclick="play_album('<%= album.youtube_hash %>')">
      <a class="list-group-item" id="<%= album.youtube_hash %>">
        <h5 class="list-group-item-heading"><%= album.title %></h4>
        <p><%= album.artist %> | contents provided by <%= get_content_provider_full_name album.content_provider %></p>
      </a>
    </div>
  <% end %>
  </div>
<% end %>


<script type="text/javascript" charset="utf-8">
    <% # Custom Music Player implemented by AJAX %>
    function new_custom_album() {
        $("a").removeClass("active");
        $.ajax({ url: "<%= albums_path %>",
                type: "post",
                data: { custom_album_query: $("#custom_album_query").val() },

                success: function(data) {
                    var embed_url = "http://www.youtube.com/embed/" + data.youtube_hash + "?autoplay=1";
                    var youtube_player = document.querySelector("iframe#youtube_player");
                    youtube_player.src = embed_url

                    var background_image= document.querySelector("img#bg");
                    var thumbnail_url = "http://i1.ytimg.com/vi/" + data.youtube_hash + "/mqdefault.jpg";
                    background_image.src = thumbnail_url;
                    }
            })
        };

    function play_album(youtube_hash) {
        $("a").removeClass("active");
        var youtube_player = document.querySelector("iframe#youtube_player");
        var embed_url = "http://www.youtube.com/embed/" + youtube_hash + "?autoplay=1";
        youtube_player.src = embed_url;
        $("a#"+youtube_hash).addClass("active");

        var background_image= document.querySelector("img#bg");
        var thumbnail_url = "http://i1.ytimg.com/vi/" + youtube_hash + "/mqdefault.jpg";
        background_image.src = thumbnail_url;
    }
</script>

app/views/daum_albums/index.html.erb
<h1>daum_albums#index</h1>
<%= @daum_albums.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Humhum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/melon_albums/index.html.erb
<h1>melon_albums#index</h1>
<%= @melon_albums.inspect %>

app/views/naver_albums/index.html.erb
<h1>naver_albums#index</h1>
<%= @naver_albums.inspect %>